version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_sql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  flask_app:
    build:
      context: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: my_database
    env_file:
      - .env
    expose:
      - "5000"
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    restart: always
    depends_on:
      - flask_app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro     
volumes:
  mysql_data:
